[project]
name = "scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.0.2",
    "scrapy>=2.12.0",
    "scrapy-playwright>=0.0.43",
]
