import scrapy

class AirbnbItem(scrapy.Item):
    id = scrapy.Field()
    title = scrapy.Field()
    property_type = scrapy.Field()
    location = scrapy.Field()
    price_per_night = scrapy.Field()
    currency = scrapy.Field()
    total_price = scrapy.Field()
    image_urls = scrapy.Field()
    ratings = scrapy.Field()
    description = scrapy.Field()
    reviews = scrapy.Field()
    number_of_reviews = scrapy.Field()
    review_tags = scrapy.Field()
    amenities = scrapy.Field()
    total_amenities_count = scrapy.Field() 
    host = scrapy.Field()
    amenities_metadata = scrapy.Field()  
    cleaning_fee = scrapy.Field()  
    service_fee = scrapy.Field() 
