# Generated by Django 5.1.7 on 2025-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_amenities_alter_listing_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10, null=True),
        ),
    ]
