export const mockListings = [
	{
		id: "1",
		title: "Luxury Beachfront Villa with Infinity Pool",
		location: "Malibu, California",
		address: "123 Ocean Drive, Malibu, CA",
		price_per_night: 650,
		currency: "USD",
		total_price: 4550,
		images: [
			"/placeholder.svg?height=500&width=500&text=Luxury+Villa",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Kitchen",
			"/placeholder.svg?height=500&width=500&text=Pool",
			"/placeholder.svg?height=500&width=500&text=Beach+View",
		],
		ratings: 4.98,
		description:
			"Experience luxury living in this stunning beachfront villa. Wake up to panoramic ocean views and fall asleep to the sound of waves. This spacious property features an infinity pool, gourmet kitchen, and direct beach access.\n\nPerfect for family gatherings or a luxurious getaway with friends. The villa is designed with high-end finishes and comes fully equipped with all modern amenities.",
		reviews: 124,
		amenities: [
			"WiFi",
			"Kitchen",
			"Free parking",
			"Pool",
			"Beach access",
			"Air Conditioning",
		],
		host: {
			name: "Michael",
			image: "/placeholder.svg?height=100&width=100&text=Michael",
			is_superhost: true,
		},
		property_type: "Villa",
		guests: 8,
		bedrooms: 4,
		beds: 5,
		bathrooms: 3.5,
		cleaning_fee: 200,
	},
	{
		id: "2",
		title: "Modern Downtown Loft with City Views",
		location: "New York, New York",
		address: "456 Broadway, New York, NY",
		price_per_night: 320,
		currency: "USD",
		total_price: 2240,
		images: [
			"/placeholder.svg?height=500&width=500&text=Modern+Loft",
			"/placeholder.svg?height=500&width=500&text=Living+Room",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Kitchen",
			"/placeholder.svg?height=500&width=500&text=City+View",
		],
		ratings: 4.85,
		description:
			"Stay in the heart of Manhattan in this stylish loft apartment. Floor-to-ceiling windows offer breathtaking views of the city skyline. The open-concept design features high-end furnishings and modern art.\n\nWalk to popular restaurants, theaters, and attractions. Perfect for couples or business travelers looking for an authentic NYC experience.",
		reviews: 97,
		amenities: [
			"WiFi",
			"Kitchen",
			"TV",
			"Air Conditioning",
			"Washer/Dryer",
			"Gym access",
		],
		host: {
			name: "Sarah",
			image: "/placeholder.svg?height=100&width=100&text=Sarah",
			is_superhost: true,
		},
		property_type: "Apartment",
		guests: 3,
		bedrooms: 1,
		beds: 2,
		bathrooms: 1,
		cleaning_fee: 100,
	},
	{
		id: "3",
		title: "Charming Cottage in Wine Country",
		location: "Napa, California",
		address: "789 Vineyard Lane, Napa, CA",
		price_per_night: 275,
		currency: "USD",
		total_price: 1925,
		images: [
			"/placeholder.svg?height=500&width=500&text=Wine+Country+Cottage",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Kitchen",
			"/placeholder.svg?height=500&width=500&text=Garden",
			"/placeholder.svg?height=500&width=500&text=Vineyard+View",
		],
		ratings: 4.92,
		description:
			"Escape to this idyllic cottage surrounded by vineyards in the heart of Napa Valley. This recently renovated property combines rustic charm with modern comforts. Enjoy your morning coffee on the private patio overlooking the rolling hills.\n\nPerfect location for wine tasting tours, with dozens of world-class wineries within a short drive. The cottage comes with a fully equipped kitchen and a cozy fireplace for chilly evenings.",
		reviews: 83,
		amenities: [
			"WiFi",
			"Kitchen",
			"Free parking",
			"Fireplace",
			"Patio",
			"Coffee maker",
		],
		host: {
			name: "David",
			image: "/placeholder.svg?height=100&width=100&text=David",
			is_superhost: false,
		},
		property_type: "Cottage",
		guests: 4,
		bedrooms: 2,
		beds: 2,
		bathrooms: 1.5,
		cleaning_fee: 120,
	},
	{
		id: "4",
		title: "Room in Chennai",
		location: "Chennai, India",
		address: "101 Pine Trail, Chennai, India",
		price_per_night: 10784,
		currency: "INR",
		total_price: 75488,
		images: [
			"/placeholder.svg?height=500&width=500&text=Chennai+Room",
			"/placeholder.svg?height=500&width=500&text=Living+Room",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Bathroom",
			"/placeholder.svg?height=500&width=500&text=Outside+View",
		],
		ratings: 4.92,
		description:
			"Stay with Mahesh at The Nook. This cozy room in Chennai offers a comfortable single bed with a private attached bathroom. Perfect for solo travelers looking for an authentic local experience.\n\nThe property is conveniently located with easy access to public transportation and local attractions. Music copyrights biz.",
		reviews: 297,
		amenities: [
			"WiFi",
			"Private bathroom",
			"Air Conditioning",
			"Workspace",
			"Local guides",
		],
		host: {
			name: "Mahesh",
			image: "/placeholder.svg?height=100&width=100&text=Mahesh",
			is_superhost: true,
		},
		property_type: "Room",
		guests: 1,
		bedrooms: 1,
		beds: 1,
		bathrooms: 1,
		cleaning_fee: 500,
	},
	{
		id: "5",
		title: "Room in Chennai - The Farm House",
		location: "Chennai, India",
		address: "202 Palm Beach Road, Chennai, India",
		price_per_night: 7649,
		currency: "INR",
		total_price: 53543,
		images: [
			"/placeholder.svg?height=500&width=500&text=Chennai+Farm+House",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Kitchen",
			"/placeholder.svg?height=500&width=500&text=Garden",
			"/placeholder.svg?height=500&width=500&text=Farm+View",
		],
		ratings: 4.93,
		description:
			"Stay with Rahul at The Farm House - Part 2. This comfortable room in Chennai offers a peaceful retreat from the busy city life. Hosting for 4 years, Rahul provides an authentic local experience with modern amenities.\n\nThe property features beautiful gardens and a relaxing atmosphere. Perfect for travelers looking to experience the real Chennai.",
		reviews: 30,
		amenities: [
			"WiFi",
			"Kitchen",
			"Garden access",
			"Air Conditioning",
			"Breakfast",
			"Parking",
		],
		host: {
			name: "Rahul",
			image: "/placeholder.svg?height=100&width=100&text=Rahul",
			is_superhost: false,
		},
		property_type: "Room",
		guests: 2,
		bedrooms: 1,
		beds: 1,
		bathrooms: 1,
		cleaning_fee: 400,
	},
	{
		id: "6",
		title: "Independent Studio Room in Adyar",
		location: "Adyar, Chennai, India",
		address: "303 Beacon Street, Adyar, Chennai",
		price_per_night: 12809,
		currency: "INR",
		total_price: 89663,
		images: [
			"/placeholder.svg?height=500&width=500&text=Adyar+Studio",
			"/placeholder.svg?height=500&width=500&text=Living+Room",
			"/placeholder.svg?height=500&width=500&text=Bedroom",
			"/placeholder.svg?height=500&width=500&text=Kitchen",
			"/placeholder.svg?height=500&width=500&text=Study",
		],
		ratings: 4.92,
		description:
			"Experience the charm of Adyar in this beautifully designed independent studio room. The space features a comfortable bed and modern amenities for a pleasant stay in Chennai.\n\nLocated in the desirable Adyar neighborhood, you'll be close to restaurants, shops, and local attractions. The studio is perfect for solo travelers or couples looking for a private space in Chennai.",
		reviews: 24,
		amenities: [
			"WiFi",
			"Private entrance",
			"Air Conditioning",
			"TV",
			"Refrigerator",
			"Hot water",
		],
		host: {
			name: "Priya",
			image: "/placeholder.svg?height=100&width=100&text=Priya",
			is_superhost: true,
		},
		property_type: "Studio",
		guests: 2,
		bedrooms: 1,
		beds: 1,
		bathrooms: 1,
		cleaning_fee: 600,
	},
];
